Major overhaul: Style fixes + minor bug fixes
It's a bit messy. And quite random. Perhaps I missed a few things.

diff --git a/bin/cmdcharts b/bin/cmdcharts
--- a/bin/cmdcharts
+++ b/bin/cmdcharts
@@ -1,70 +1,69 @@
 #!/usr/bin/env sh
 
-# Print most used commands.
+# Print most used shell commands.
 
-SCRIPTFILE="$(basename "$0")"
+set -e
+
+# Constants:
+RUNNAME="$(basename "$0")"
+E_SUCCESS=0
+E_USER=1
+E_MISC=2
+E_INTERNAL=4
 
 die()
 {
-	die_retval=$1
-	die_format="$2"
+	retval=$1
+	format="$2"
 	shift 2
-	printf "$die_format" "$@" >&2
+	printf "$format" "$@" >&2; echo >&2
 	exit $retval
 }
 
 chart()
 {
-	[ -n "$HISTFILE" ] || die 2 "HISTFILE undefined: can't locate shell history"
-	[ -e "$HISTFILE" ] || die 2 '%s not found' "$HISTFILE"
-	if [ -z "$COMMAND" ]; then
+	test -n "$HISTFILE" || die $E_MISC "HISTFILE undefined: can't locate shell history"
+	test -e "$HISTFILE" || die $E_MISC '%s not found' "$HISTFILE"
+	if [ -z "$command" ]; then
 		awk '{print $1}' < "$HISTFILE"
 	else
-		grep --text "^$COMMAND" "$HISTFILE" | awk "{print \$$(($COMMANDLEN+1))}"
-	fi | sort | uniq -c | sort -rn | head -n "$NLINES"
+		grep --text "^$command" "$HISTFILE" | awk "{print \$$((commandlen + 1))}"
+	fi | sort | uniq -c | sort -rn | head -n "$nlines"
 }
 
 usage()
 {
 	cat >&2 <<- EOF
-	$SCRIPTFILE: list most used commands
+	$RUNNAME: list most used commands
 
-	Usage: $SCRIPTFILE [OPTIONS] [COMMAND]
+	Usage: $RUNNAME [OPTIONS] [COMMAND]
 
 	Options:
 	    -h            Display this help
-	    -n NLINES     List NLINES most used commands [default=$NLINES]
+	    -n NLINES     List NLINES most used commands [default=$nlines]
 
 	Command:
 	    If present, display commands with COMMAND as suffix (e.g. sudo, git, vim)
 	EOF
-	exit 1
 }
 
-main()
-{
-	NLINES=10
-	COMMAND=''
+# Options:
+nlines=10
+command=''
+while getopts :hn: opt; do
+	case "$opt" in
+		h) usage; exit $E_SUCCESS ;;
+		n) nlines="$OPTARG" ;;
+		'?') die $E_USER 'Illegal option: -%s' "$OPTARG" ;;
+		*) die $E_INTERNAL 'Internal error' ;;
+	esac
+done
+shift $((OPTIND - 1))
 
-	# Options
-	while getopts hn: opt; do
-		case "$opt" in
-			h) usage ;;
-			n) NLINES="$OPTARG" ;;
-			*) usage ;;
-		esac
-	done
-	shift $(($OPTIND - 1))
+# Command:
+command="$*"
+commandlen=$#
+[ -n "$command" ] && shift
 
-	# Command:
-	COMMAND="$@"
-	COMMANDLEN=$#
-	[ -n "$COMMAND" ] && shift
-
-	# Test validity:
-	#test $# -eq 0 || die 1 'Trailing arguments: %s' "$@"
-
-	chart
-}
-
-main "$@"
+# Chart:
+chart
diff --git a/bin/pdfcat b/bin/pdfcat
--- a/bin/pdfcat
+++ b/bin/pdfcat
@@ -1,76 +1,77 @@
 #!/usr/bin/env sh
 
-appname="$(basename "$0")"
+set -e
+
+APPNAME="$(basename "$0")"
+E_SUCCESS=0
+E_USER=1
+E_MISC=2
+E_INTERNAL=4
+FALSE=0
+TRUE=1
 
 die()
 {
-	die_retval=$1
-	die_format="$2"
-	shift 2
-	printf "$die_format\n" "$@" >&2
-	exit $die_retval
-}
-
-die_help()
-{
-	die 1 'Run `%s -h` for help' "$appname"
-}
-
-concatenate()
-{
-	# Check input files:
-	for i in "$@"; do
-		test -e "$i" || die 2 '%s: File not found' "$i"
-		filetype="$(file --mime --brief "$i" | cut -d ';' -f 1)"
-		test "$filetype" = 'application/pdf' || die 2 '%s: Not a PDF file' "$i"
-	done
-
-	# Check output file:
-	if [ -e "$OUT" ] && [ $FORCE -ne 0 ]; then
-		die 2 '%s: File already exists' "$OUT"
+	retval=$1; shift
+	printf "$@" >&2; echo >&2
+	if [ $retval -eq $E_USER ]; then
+		printf 'Run with -h for help\n' >&2
 	fi
-
-	# Ghostscript:
-	gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile="$OUT" "$@"
+	exit $retval
 }
 
 usage()
 {
 	cat >&2 <<- EOF
-	${appname}: Concatenate PDF files
+	$APPNAME: Concatenate PDF files
 
-	Usage: ${appname} [OPTION ...] OUT IN1 IN2 [IN3 ...]
+	Usage: $APPNAME [OPTION ...] OUT IN1 IN2 [IN3 ...]
 
 	Options:
-		-f    Overwrite output PDF if it already exists
-		-h    Display this help
+	  -f    Overwrite output PDF if it already exists
+	  -h    Display this help
 	EOF
 	exit 1
 }
 
-main()
+concatenate()
 {
-	# Options:
-	FORCE=1
-	while getopts fh opt; do
-		case "$opt" in
-			f) FORCE=0 ;;
-			h) usage ;;
-			'?') die_help ;;
-		esac
+	# Check input files:
+	for infile in "$@"; do
+		test -e "$infile" || die $E_MISC '%s: File not found' "$infile"
+		filetype="$(file --mime --brief "$infile" | cut -d ';' -f 1)"
+		test "$filetype" = 'application/pdf' || \
+			die $E_MISC '%s: Not a PDF file' "$infile"
 	done
-	shift $(($OPTIND - 1))
 
-	# Output:
-	OUT="$1"
-	test -n "$OUT" || usage
-	shift
+	# Check output file:
+	if [ -e "$outfile" ] && [ $force -ne $TRUE ]; then
+		die $E_MISC '%s: File already exists' "$outfile"
+	fi
 
-	# Input:
-	test $# -ge 2 || usage
-
-	# Concatenate:
-	concatenate "$@"
+	# Ghostscript:
+	gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile="$outfile" "$@"
 }
 
-main "$@"
+# Options:
+force=$FALSE
+while getopts :fh opt; do
+	case "$opt" in
+		f) force=$TRUE ;;
+		h) usage; exit $E_SUCCESS ;;
+		'?') die $E_USER 'Unknown option: -%s' "$OPTARG" ;;
+		*) die $E_INTERNAL 'Unhandled option: -%s' "$opt" ;;
+	esac
+done
+shift $((OPTIND - 1))
+
+# Output:
+outfile="$1"
+test -n "$outfile" || die $E_USER 'Missing output file'
+shift
+
+# Input:
+test $# -ge 2 || die $E_USER 'Please provide at least 2 input files'
+
+# Concatenate:
+concatenate "$@"
diff --git a/bin/rdp b/bin/rdp
--- a/bin/rdp
+++ b/bin/rdp
@@ -1,15 +1,16 @@
 #!/usr/bin/env sh
 
 # Simple frontend to xfreerdp - takes a hostname and reads the corresponding
-# configuration file from $HOME/.local/etc/rdp/
-
+# configuration file from $XDG_CONFIG_HOME/freerdp/hosts
+#
 # Written by ayekat on a cool monday morning in may 2016
 
+HOME="${HOME:-$(getent passwd "$(id -u)" | cut -d: -f6)}"
 XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
+
 CONFDIR="$XDG_CONFIG_HOME/freerdp/hosts"
 APPNAME="$(basename "$0")"
-EDITOR="${EDITOR:-/usr/bin/nano}"
-
+EDITOR="${VISUAL:-${EDITOR:-/usr/bin/vi}}"
 E_SUCCESS=0
 E_FAIL=1
 E_USER=2
@@ -17,15 +18,13 @@ E_PERM=3
 TRUE=1
 FALSE=0
 
-usage() { echo "Usage: $APPNAME [OPTIONS] HOST"; }
-
-help()
+usage()
 {
-	echo "$APPNAME: Establish an RDP connection to a host"
-	echo
-	usage
-	echo
 	cat <<- EOF
+	$APPNAME: Establish an RDP connection to a host
+
+	Usage: $APPNAME [OPTIONS] HOST
+
 	Options:
 	  -e, --edit        Launch editor for the host config file, then exit
 	  -h, --help        Display this message and exit
@@ -39,16 +38,12 @@ help()
 
 die()
 {
-	retval_str=$1
-	retval=$(eval "echo \$$retval_str")
-	shift
-	format="$1"
-	if [ -n "$format" ]; then
-		shift
-		printf "\033[31m$retval_str\033[0m $format\n" "$@" >&2
+	retval=$1; shift
+	if [ $# -gt 0 ]; then
+		printf "$@" >&2; echo >&2
 	fi
 	if [ $retval -eq $E_USER ]; then
-		usage >&2
+		printf 'Run with --help for help.\n' >&2
 	fi
 	exit $retval
 }
@@ -66,23 +61,27 @@ options=''
 edit=$FALSE
 while [ $# -gt 0 ]; do
 	case "$1" in
-		-e|--edit) edit=$TRUE ;;
-		-h|--help) help; exit 0 ;;
-		-l|--list) list; exit 0 ;;
-		-o|--option) shift; options="$options $1" ;;
-		-*) die E_USER "Unknown option: -$1" ;;
-		*) break ;;
+		(-e|--edit) edit=$TRUE ;;
+		(-h|--help) usage; exit $E_SUCCESS ;;
+		(-l|--list) list; exit $E_SUCCESS ;;
+		(-o|--option) test $# -ge 2 || die $E_USER 'Missing argument for %s' "$1"
+			          shift; options="$options $1" ;;
+		(-*) die $E_USER 'Unknown option: %s' "$1" ;;
+		(*) break ;;
 	esac
 	shift
 done
 host="$1"
-test -n "$host" || die E_USER "Please specify a host"
+test -n "$host" || die $E_USER 'Please specify a host'
+shift
+
+test $# -eq 0 || die $E_USER 'Trailing arguments: %s' "$*"
 
 # Check environment:
-test -d "$CONFDIR" || die E_FAIL "$CONFDIR: No such directory"
-test -r "$CONFDIR" || die E_PERM "$CONFDIR: Permission denied"
+test -d "$CONFDIR" || die $E_FAIL '%s: No such directory' "$CONFDIR"
+test -r "$CONFDIR" || die $E_PERM '%s: Permission denied' "$CONFDIR"
 hostfile="$CONFDIR/${host}.rdp"
-test -e "$hostfile" || die E_FAIL "$hostfile: No such file"
+test -e "$hostfile" || die $E_FAIL '%s: No such file' "$hostfile"
 
 if [ $edit -eq $TRUE ]; then
 	# Edit RDP connection:
