dotbloat: Some cosmetic updates in the code
Also handle `cd $HOME` error condition case.

diff --git a/bin/dotbloat b/bin/dotbloat
--- a/bin/dotbloat
+++ b/bin/dotbloat
@@ -1,19 +1,21 @@
 #!/usr/bin/env sh
 # Lists some statistics about the number of files in $HOME
 
-nondots="$(find "$HOME" -maxdepth 1 -mindepth 1 -name '[^.]*')"
-dots="$(find "$HOME" -maxdepth 1 -mindepth 1 -name '.*')"
-n_nondots="$(printf "%s\n" "$nondots" | wc -l)"
-n_dots="$(printf "%s\n" "$dots" | wc -l)"
+set -eu
+
+HOME="${HOME:-$(getent passwd "$(id -un)" | cut -d : -f 6)}"
+
+n_nondots="$(find "$HOME" -maxdepth 1 -mindepth 1 -name '[^.]*' | wc -l)"
+n_dots="$(find "$HOME" -maxdepth 1 -mindepth 1 -name '.*' | wc -l)"
 n_all=$((n_nondots + n_dots))
 
 prompt_delete() {
 	printf 'Delete %s? [Y/n] ' "$1"
 	read -r a
 	case "$a" in
-		''|Y*|y*) rm -rv "$1" ;;
-		N*|n*) ;;
-		*) prompt_delete "$1" ;;
+		(''|Y*|y*) rm -rv "$1" ;;
+		(N*|n*) ;;
+		(*) prompt_delete "$1" ;;
 	esac
 }
 
@@ -21,12 +23,15 @@ prompt_delete() {
 cat <<- EOF
 total:        $n_all
 normal files: $n_nondots
-$(printf "\033[1m")dotfiles:     $n_dots$(printf "\033[0m")
+$(printf '\033[1m')dotfiles:     $n_dots$(printf '\033[0m')
 
 EOF
 
 # list:
-cd
+if ! cd "$HOME"; then
+	echo "Could not cd into home directory ($HOME)" >&2
+	exit 1
+fi
 ls -1d --color=auto .[!.]*
 
 # delete:
