scr: Fix screen names - and general code overhaul

diff --git a/bin/scr b/bin/scr
--- a/bin/scr
+++ b/bin/scr
@@ -1,65 +1,101 @@
-#!/usr/bin/env sh
+#!/bin/sh --
+
 # Script for simplifying on-the-go addition of a VGA/HDMI-monitor to my laptop.
 # Written by ayekat on a boring january day; improved in october 2013; improved
 # again to support HDMI screens in april 2014.
 
-# basic values
-appname="$(basename "$0")"
-cmd="$1"
-shift
+set -eu
 
-# screen names
-lcdname=LVDS1
-case "$appname" in
-	(vga) scrname=VGA1 ;;
-	(hdmi) scrname=HDMI1 ;;
-	(dp) scrname=DP1 ;;
-	(*) echo "Please invoke this script as 'vga', 'hdmi' or 'dp'." >&2; exit 1 ;;
-esac
+# Basic values:
+APPNAME="$(basename "$0")"
+LCDNAME=LVDS-1
 
-scr_add() {
-	# mode:
-	modeline="$(xrandr | grep -A 1 "$scrname connected" | tail -n +2)"
-	if [ -z "$modeline" ]; then
-		printf "[%s] %s is not connected\n" "$appname" "$scrname"
-		exit 1
-	fi
+E_SUCCESS=0
+E_USER=1
+E_CONN=2
+E_INTERNAL=13
 
-	# position:
+scr_add()
+{
+	# Mode:
+	modeline="$(xrandr | grep -A 1 "$SCRNAME connected" | tail -n +2)"
+	test -n "$modeline" || die $E_CONN '%s is not connected' "$SCRNAME"
+
+	# Position:
 	position="$1"
 	case "$position" in
 		(right|left) position="$position-of";;
 	esac
-	xrandr --output "$lcdname" --auto || exit 1
-	xrandr --output "$scrname" --auto --"$position" "$lcdname" --primary || exit 1
+	xrandr --output "$LCDNAME" --auto || exit 1
+	xrandr --output "$SCRNAME" --auto --"$position" "$LCDNAME" --primary || exit 1
 	scr_setup
 }
 
 scr_remove() {
-	printf "[%s] %s: removing %s...\n" "$(date +%H:%M:%S)" "$appname" "$scrname"
-	xrandr --output "$scrname" --off || exit 1
+	printf 'Removing %s...\n' "$SCRNAME"
+	xrandr --output "$SCRNAME" --off \
+		|| die $E_CONN 'Could not remove %s' "$SCRNAME"
 	scr_setup
 }
 
-scr_setup() {
-	xrandr --output "$lcdname" --dpi 96
+scr_setup()
+{
+	xrandr --output "$LCDNAME" --dpi 96
 	nitrogen --restore
 }
 
-scr_help() {
-	printf "%s add (right|left|above|below)|remove\n" "$appname"
+print_help()
+{
+	cat <<- EOF
+	$APPNAME: Quickly add/remove external screens
+
+	Usage: $APPNAME add {right|left|above|below}
+	       $APPNAME remove
+	EOF
 }
 
-# detect action
+die()
+{
+	retval=$(($1)); shift
+	printf "$@" >&2; echo >&2
+	if [ $retval -eq $E_USER ]; then
+		echo 'Run with -h for more detail' >&2
+	fi
+	exit $retval
+}
+
+# What kind of screen?
+case "$APPNAME" in
+	(vga) SCRNAME=VGA-1 ;;
+	(hdmi) SCRNAME=HDMI-1 ;;
+	(dp) SCRNAME=DP-1 ;;
+	(*) die $E_USER 'Please invoke this script as vga, hdmi or dp' ;;
+esac
+
+# Options:
+while getopts :h opt; do
+	case "$opt" in
+		(h) print_help; exit $E_SUCCESS ;;
+		(:) die $E_USER 'Missing argument for -%s' "$OPTARG" ;;
+		('?') die $E_USER 'Unknown option -%s' "$OPTARG" ;;
+		(*) die $E_INTERNAL 'Unhandled option -%s' "$OPTARG" ;;
+	esac
+done
+test $# -gt 0 || die $E_USER 'Please provide a command'
+cmd="$1"; shift
+
+# Action:
 case "$cmd" in
 	(add)
-		[ $# -ne 1 ] && { vga_help; exit 1; }
-		scr_add "$@";;
-
+		test $# -gt 0 || die $E_USER 'Please provide a position'
+		scr_add "$@"
+		;;
 	(remove)
-		scr_remove;;
-
+		test $# -eq 0 || die $E_USER 'Trailing arguments: %s' "$*"
+		scr_remove
+		;;
 	(*)
-		scr_help
+		die $E_USER 'Unknown command: %s' "$cmd"
+		;;
 esac
 
