tmux-view: Disallow characters in IFS and colons
This is simpler - and really, this is just a personal script, so it's an
acceptable amount of "dirty".

diff --git a/bin/tmux-view b/bin/tmux-view
--- a/bin/tmux-view
+++ b/bin/tmux-view
@@ -5,17 +5,26 @@ set -eu
 # Check that we're not running in tmux already:
 test -z "${TMUX:-}" || tmux # should error out due to `set -e`
 
-# Check that base session exists:
+# Session names:
 base="base_${1:-default}"
+view="view_$(date '+%Y%m%d%H%M%S')" # FIXME more robust "unique" view ID
+
+# Disallow certain characters in session name:
+colon=':' space=' ' tab='	' newline='
+'
+case "$base" in (*$colon*|*$space*|*$tab*|*$newline*)
+	echo "Invalid base session name: $base" >&2
+	exit 1
+esac
+unset colon space tab newline
+
+# Check that base session exists:
 tmux has-session -t "$base" 2>/dev/null || tmux new-session -d -s "$base"
 
 # Create view session and link to base session:
-view="view_$(date '+%Y%m%d%H%M%S')" # FIXME more robust "unique" view ID
 tmux new-session -s "$view" -t "$base"
 
 # Kill detached view sessions linked to our base session:
-IFS='
-'
 for s in $(tmux ls -F '#{session_group}:#{session_name}:#{session_attached}'); do
 	case "$s" in ($base:*:0) ;; (*) continue; esac
 	case "$s" in ($base:$base:*) continue ;; esac
